import { decrypt } from "@/app/auth/session";
import { Types } from "mongoose";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { MessageContextProvider } from "./context/MessageContext";
import { UserContextProvider } from "./context/UserContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await cookies()).get("session")?.value;

  // Decrypt and extract userId (if needed)
  const decryptedSession = await decrypt(session);
  const userId = decryptedSession ? decryptedSession.userId : null;
  console.log(`userId from root: ${userId}`);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MessageContextProvider>
          <UserContextProvider>{children}</UserContextProvider>
        </MessageContextProvider>
      </body>
    </html>
  );
}
